apiVersion: v1
kind: Pod
metadata: 
  name: java-app
spec:
  containers:
  - name: java-app-container
    image: adkham01/java-app
  affinity:    
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - Large
          - key: size
            # Exists operator will simply check if the label "size" exists or not
            # operator:Exists
            operator: NotIn
            values:
            - Small    
