apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    ports:  
    - containerPort: 8080
    priorityClassName: high-priority    
