apiVersion: v1
kind: Pod 
metadata:
  name: java-app
  labels:
    app: java
spec: 
  containers:
  - name: java-app
    image: adkham01/java-app
    tolerations:
    - key: "app"
      operator: "Equal"
      value: "java" 
      effect: "NoSchedule"
