version: '3.8'

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

volumes:
  db-data:
    driver: local

services:
  redis:
    image: "redis:alpine"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s  
      restart_policy:
        condition: on-failure

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        max_replicas_per_node: 1

  vote:
    image: "dockersamples/examplevotingapp_vote:latest"
    ports:
      - "5000:80"
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s  
      restart_policy:
        condition: on-failure

  result:
    image: "dockersamples/examplevotingapp_result:latest"
    ports:
      - "5001:80"
    networks:
      - backend
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s  
      restart_policy:
        condition: on-failure      

  worker:
    image: "dockersamples/examplevotingapp_worker:latest"
    networks:
      - frontend
      - backend
    depends_on:
      - redis
      - db
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=VOTING]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1