apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: admin-crt
spec:
  signerName: kubernetes.io/kube-apiserver
  expirationSeconds: 600
  usages:
    - client auth
  request: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dqQ0NBVUlDQVFBd0ZURVRN
    QkVHQTFVRUF3d0thM1ZpWlMxaFpHMXBiakNDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBB
    RENDQVFvQ2dnRUJBT2h5cTA0clFzd2ZvdjVjekRvV1UzYlZnK09mUHZIMlIyd3lFS3dICnJUNjNk
    dUxCYmJxMThaMmh1MFp6MXVvd0hYeTV1YVF5UTQ5OGhsYVk1b3BpQ2pNTkR5RHRTeENYbVowS0F5
    K3AKL0NISENBaDk3TFhPOWFDUVhUQWtzd2c4RUgwNXpnWGJUVmJvNGF0MmlSVXZNNFB1YW0xbGNT
    Mm1WLzJQbDVOYwoyV1NMZTZ1eGl5L21xWDJ4NDRFTlhMb2lIQVhFYS9acVRrdFg0Rm5SRHltY05O
    aVhvY2Ira3RrWDF4Q2JNT1FmCmlrQlVta3p0VlpmQ2gvVm5YTnZlOEV1ZUIxQ2VCN1JkSUlDclht
    L2lBVFRXRGZET1VqcVlkQkpIYUlaQWNnM0MKaEx3VHBaQklXOHpXMDlFN2dmQjdFVk8zanJSUnpw
    YlhHNEs3OFZZSk81RHg3bDBDQXdFQUFhQUFNQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCQVFER0J2
    VXp4TlppZWM0OTRqOFhIY1lFZkpXYjl4Tlk0R1dCajVvMTR0V25GSTY4CnJQR0QvRFhlQytUejM4
    NzV4TXFDUXNmK1dTYkNDRTNxK2crSDVxVEJYNy9nSDBJbnlwL0VLTHhKRXRDZUx3UVgKTzljUVFJ
    MWpJclVBeFpoazdQd0x6T2tyZjd2NlE1Z3AxY0d0cy9peW9sdHBYdFFEdURUREprRG91RFRBVHUr
    dgoxT2RZWWFOTmFxanNlLzgyQnBIQ1Z1b21QWkUwOUdmZzJjVElxaWsrUFJTN1hXTG5LTnBycDNu
    YkttWEVpczNkCmZsSk5OWEo0ckptMTZteTdNWnM2QVQ2RE9wZExobERXRmc3VEY5MjF1cnU3bk9m
    SjJJcStUbG1OeWY2NFlwMmwKekkvOTFJb2RBYng0dzR2Z1dWeTFmcFcyN3VPejhaRnNsVXlieWdX
    ZAotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0=
