apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources: 
- resorces:
  - secrets
  providers:
  - identity: {}
  - aesgcm:
      keys:
      - name: user 
        secret: dXNlcg==  
      - name: user2
        secret: dXNlcjI=
              
