#!bin/bash

# Create veth pair
ip link add ...

# Attach veth pair
ip link set ... netns ...
ip link set ... netns ...

# Assign IP address
ip -n <namespace1> addr add ...
ip -n <namespace2> route add ...

# Bring Up Interface
ip -n <namespace1> link set ... up
