name: Basic Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  build-image:
    if: false
    name: Build build-image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    
      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
        # this is for building and pushing the image to Docker Hub
        # this pushes the image only after merge to main branch
          # push: ${{ github.event_name != 'pull_request' }}
          push: false
          tags: adkham01/all-hands:latest    