apiVersion: v1
kind: Pod
metadata:
  name: simple-web-app
  labels:
    app.kubernetes.io/name: simple-web-app
spec:
  containers:
    - name: simple-web-app
      image: simple-web-app
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret
